# Datasource configuration
spring.datasource.url=${DB_URL:jdbc:postgresql://${RDS_HOSTNAME:localhost}:${RDS_PORT:5432}/${RDS_DB_NAME:pmd_agile}}
spring.datasource.username=${DB_USER:${RDS_USERNAME:}}
spring.datasource.password=${DB_PASSWORD:${RDS_PASSWORD:}}
spring.datasource.driver-class-name=org.postgresql.Driver
# JPA/Hibernate configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.database=postgresql
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# Jira API configuration
jira.api.baseurl=${JIRA_API_BASEURL:http://localhost}
jira.redirect.url=${JIRA_REDIRECT_URL:}
jira.callback.url=${JIRA_CALLBACK_URL:}
jira.oauth.api.cloud.id.url=${JIRA_OAUTH_CLOUD_ID_URL:http://localhost}
jira.oauth.api.token.url=${JIRA_OAUTH_TOKEN_URL:http://localhost}
jira.oauth.client.id=${JIRA_CLIENT_ID:}
jira.oauth.client.secret=${JIRA_CLIENT_SECRET:}
# Mail configuration
spring.mail.host=${SMTP_HOST:}
spring.mail.port=${SMTP_PORT:}
spring.mail.username=${SMTP_USERNAME:}
spring.mail.password=${SMTP_PASSWORD:}
spring.mail.properties.mail.smtp.trust=${SMTP_TRUST:*}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=${SMTP_STARTTLS_ENABLE:false}
spring.mail.properties.mail.smtp.starttls.required=${SMTP_STARTTLS_REQUIRED:false}
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=3000
spring.mail.properties.mail.smtp.writetimeout=5000
application.mailing.from=${MAIL_FROM:}
application.mailing.frontend.activation-url=${FRONTEND_BASE_URL:}/activate-account
application.mailing.frontend.reset-password-url=${FRONTEND_BASE_URL:}/reset-password
# Application specific configuration
application.security.jwt.secret-key=${JWT_SECRET_KEY}
application.security.jwt.expiration=86400000
application.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:4200}
server.port=${PORT:5000}
server.max-http-request-header-size=65536