# Datasource configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/pmd_agile
spring.datasource.username=username
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver
# JPA/Hibernate configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database=postgresql
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# Jira API configuration
jira.api.baseurl=https://api.atlassian.com/ex/jira/
jira.redirect.url=${JIRA_REDIRECT_URL:}
jira.callback.url=http://localhost:4200/profile
jira.oauth.api.cloud.id.url=https://api.atlassian.com/oauth/token/accessible-resources
jira.oauth.api.token.url=https://auth.atlassian.com/oauth/token
jira.oauth.client.id=${JIRA_CLIENT_ID:}
jira.oauth.client.secret=${JIRA_CLIENT_SECRET:}
# Mail configuration
spring.mail.host=${SMTP_HOST:localhost}
spring.mail.port=${SMTP_PORT:1025}
spring.mail.username=${SMTP_USERNAME:contact@pmd-agile.com}
spring.mail.password=${SMTP_PASSWORD:}
spring.mail.properties.mail.smtp.trust=${SMTP_TRUST:*}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=${SMTP_STARTTLS_ENABLE:false}
spring.mail.properties.mail.smtp.starttls.required=${SMTP_STARTTLS_REQUIRED:false}
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=3000
spring.mail.properties.mail.smtp.writetimeout=5000
application.mailing.from=${MAIL_FROM:contact@pmd-agile.com}
application.mailing.frontend.activation-url=http://localhost:4200/activate-account
application.mailing.frontend.reset-password-url=http://localhost:4200/reset-password
# Application specific configuration
application.security.jwt.secret-key=${JWT_SECRET_KEY}
application.security.jwt.expiration=86400000
server.port=8088
server.max-http-request-header-size=65536
logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=DEBUG