spring.application.name=pmd-agile
spring.profiles.active=dev

#logging.level.org.springframework.security=TRACE

# Jira API configuration
jira.api.baseurl=
jira.oauth.api.token.url=
jira.oauth.api.cloud.id.url=
jira.redirect.url=
jira.callback.url=

spring.servlet.multipart.max-file-size=50MB
springdoc.default-produces-media-type=application/json
server.servlet.context-path=/pmd-agile

